name: Auto Merge

on:
  schedule:
   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch upstream changes
        run: git remote add upstream https://github.com/mcMMO-Dev/mcMMO.git && git fetch upstream
      - name: Merge upstream changes
        run: git merge upstream/master -m "Merge upstream changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.RELEASE_KEY }}
